/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Recepcionista;
import static Clases.ConexionBD.close;
import static Clases.ConexionBD.getConnection;
import Clases.Doctor;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author lsaic
 */
public class AgregarRecepcionista extends javax.swing.JFrame {

    int id=0;
     String Cedula="";
        String Nombre="";
        String Segundonombre="";
        String Apellido="";
        String Segundoapellido="";
        String Edad="";
        String telefono1="";
        String telefono2="";
        String genero="";
        String Direccion="";
        String Horario ="";
        ArrayList<Recepcionista>listaasistente= new ArrayList();
    /**
     * Creates new form AgregarAsistente
     */

    public AgregarRecepcionista() {
        
        initComponents();
        btnedit.setVisible(false);
        this.setLocationRelativeTo(null); 
        this.getContentPane().setBackground(Color.white);
        
        box01.setSelectedItem("Tipos");
        box01.addItem("Matutino");
        box01.addItem("Vespertino");
        box01.addItem("Nocturno");
        
        SpinnerNumberModel spinner_Edad=new SpinnerNumberModel();
        spinner_Edad.setMaximum(100);
        spinner_Edad.setMinimum(0);
        spinnerEdadAsistente.setModel(spinner_Edad);
    }
    
    public AgregarRecepcionista(int id) {
        initComponents();
        this.id=id;
        jButton1.setVisible(false);
        this.setLocationRelativeTo(null); 
        
        Connection conn = null;
        String SQL_SELECT = "SELECT * FROM pacientes WHERE id = "+id+";";
        PreparedStatement stmt = null;
        ResultSet rs = null;
        
        try {
            conn = getConnection();
            stmt = conn.prepareStatement(SQL_SELECT);
            rs = stmt.executeQuery();
            while (rs.next()) {
                String primer_nombre = rs.getString("primernombre");                
                String segundo_nombre = rs.getString("segundonombre");
                String primer_apellido = rs.getString("primerapellido");
                String segundo_apellido = rs.getString("segundoapellido");
                String cedula2 = rs.getString("cedula");
                String edad = rs.getString("edad");
                String direccion = rs.getString("direccion");
                String generoe = rs.getString("genero");
                String telefono1e = rs.getString("telefono1");
                String telefono2e = rs.getString("telefono2");
                txtCedula.setText(cedula2);
                txtPrimerNombre.setText(primer_nombre);   
                txtSegundoNombre.setText(segundo_nombre);
                txtPrimerApellido.setText(primer_apellido);
                txtSegundoApellido.setText(segundo_apellido);
                spinnerEdadAsistente.setValue(Integer.parseInt(edad));
                txtTelefono1.setText(telefono1e);
                txtTelefono2.setText(telefono2e);
                txtDireccion.setText(direccion);
               
                if(generoe.equals("Mujer")){
                    generoFasistente.setSelected(true);
                }else{
                    generoMAsistente.setSelected(true);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        } finally {
            try {
                close(rs);
                close(stmt);
                close(conn);
            } catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
        }
        
        
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnedit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        txtPrimerApellido = new javax.swing.JTextField();
        txtSegundoNombre = new javax.swing.JTextField();
        txtPrimerNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        generoMAsistente = new javax.swing.JRadioButton();
        generoFasistente = new javax.swing.JRadioButton();
        spinnerEdadAsistente = new javax.swing.JSpinner();
        box01 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        txtTelefono2 = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Registrar Recepcionista");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 40, 306, 60));

        btnedit.setText("Editar");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 153, 255));
        jLabel13.setText("Datos Personales");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 153, 255));
        jLabel14.setText("Datos Referenciales");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 339, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, -1, -1));

        jButton2.setText("Regresar al Inicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 11, -1, -1));

        jLabel6.setText("Segundo Apellido:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel5.setText("Primer Apellido:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel4.setText("Segundo Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel3.setText("Primer Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel2.setText("Cedula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        txtSegundoApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtSegundoApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSegundoApellido.setText("Ingrese el segundo apellido");
        txtSegundoApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSegundoApellidoMousePressed(evt);
            }
        });
        txtSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 288, 180, -1));

        txtPrimerApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtPrimerApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrimerApellido.setText("Ingrese el primer apellido");
        txtPrimerApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPrimerApellidoMousePressed(evt);
            }
        });
        getContentPane().add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 257, 180, -1));

        txtSegundoNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtSegundoNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSegundoNombre.setText("Ingrese el segundo nombre");
        txtSegundoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSegundoNombreMousePressed(evt);
            }
        });
        getContentPane().add(txtSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 226, 180, -1));

        txtPrimerNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtPrimerNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrimerNombre.setText("Ingrese el primer nombre");
        txtPrimerNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPrimerNombreMousePressed(evt);
            }
        });
        getContentPane().add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 195, 180, -1));

        txtCedula.setForeground(new java.awt.Color(102, 102, 102));
        txtCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCedula.setText("Ingrese la cédula");
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaMousePressed(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 162, 180, -1));

        jLabel11.setText("Género:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 165, -1, -1));

        jLabel7.setText("Edad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 198, -1, -1));

        jLabel12.setText("Horario:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 229, -1, -1));

        buttonGroup1.add(generoMAsistente);
        generoMAsistente.setText("M");
        generoMAsistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoMAsistenteActionPerformed(evt);
            }
        });
        getContentPane().add(generoMAsistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 161, -1, -1));

        buttonGroup1.add(generoFasistente);
        generoFasistente.setText("F");
        getContentPane().add(generoFasistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 161, -1, -1));

        spinnerEdadAsistente.setMaximumSize(new java.awt.Dimension(0, 99));
        spinnerEdadAsistente.setMinimumSize(new java.awt.Dimension(99, 0));
        getContentPane().add(spinnerEdadAsistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 195, 84, -1));

        box01.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horario" }));
        box01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box01ActionPerformed(evt);
            }
        });
        getContentPane().add(box01, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 226, -1, -1));

        jLabel10.setText("Dirección:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 482, -1, -1));

        jLabel9.setText("Telefono 2:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jLabel8.setText("Telefono 1:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        txtTelefono1.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono1.setText("Ingrese el número de teléfono");
        txtTelefono1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefono1MousePressed(evt);
            }
        });
        getContentPane().add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 382, 180, -1));

        txtTelefono2.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono2.setText("Ingrese el número de teléfono");
        txtTelefono2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefono2MousePressed(evt);
            }
        });
        getContentPane().add(txtTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 421, 180, -1));

        txtDireccion.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDireccion.setText("Ingrese la dirección");
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDireccionMousePressed(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 459, 180, 60));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 615, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Media/imagen_recepcion.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        if(txtCedula.getText().equals("") || txtPrimerNombre.getText().equals(" ") || txtPrimerApellido.getText().equals("") || txtTelefono1.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Hay campos vacios");
        }else{
            Recepcionista miasistente = new Recepcionista();
            Cedula=txtCedula.getText();
            Nombre=txtPrimerNombre.getText();
            Segundonombre=txtSegundoNombre.getText();
            Apellido=txtPrimerApellido.getText();
            Segundoapellido=txtSegundoApellido.getText();
            Edad=spinnerEdadAsistente.getValue().toString();
            telefono1=txtTelefono1.getText();
            telefono2=txtTelefono2.getText();
            Direccion=txtDireccion.getText();
            if(generoMAsistente.isSelected()){
                genero="Hombre";
            }
            if(generoFasistente.isSelected()){
                genero="Mujer";
            }

            miasistente.setCedula(Cedula);
            miasistente.setNombre(Nombre);
            miasistente.setSegundo_nombre(Segundonombre);
            miasistente.setApellido(Apellido);
            miasistente.setSegundo_apellido(Segundoapellido);
            miasistente.setEdad(Edad);
            miasistente.setGenero(genero);
            miasistente.setTelefono(telefono1);
            miasistente.setTelefono2(telefono2);
            miasistente.setDireccion(Direccion);

            String SQL_UPDATE="UPDATE pacientes SET cedula=?, primernombre=?, segundonombre=?, primerapellido=?, segundoapellido=?, edad=?, direccion=?, genero=?, telefono1=?, telefono2=? WHERE id="+id+";";

            Connection conn = null;
            PreparedStatement stmt = null;
            try {
                conn = getConnection();
                stmt = conn.prepareStatement(SQL_UPDATE);
                stmt.setString(1, miasistente.getCedula());
                stmt.setString(2, miasistente.getNombre());
                stmt.setString(3, miasistente.getSegundo_nombre());
                stmt.setString(4, miasistente.getApellido());
                stmt.setString(5, miasistente.getSegundo_apellido());
                stmt.setString(6, miasistente.getEdad());
                stmt.setString(7, miasistente.getDireccion());
                stmt.setString(8, miasistente.getGenero());
                stmt.setString(9, miasistente.getTelefono());
                stmt.setString(10, miasistente.getTelefono2());
                stmt.executeUpdate();
            } catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
            finally{
                try {
                    close(stmt);
                    close(conn);
                } catch (SQLException ex) {
                    ex.printStackTrace(System.out);
                }
            }

            txtDireccion.setText("");
            txtPrimerNombre.setText("");
            txtSegundoNombre.setText("");
            txtPrimerApellido.setText("");
            txtSegundoApellido.setText("");
            txtSegundoApellido.setText("");
            txtTelefono1.setText("");
            txtTelefono2.setText("");
            txtDireccion.setText("");
            new Pacientes().setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_btneditActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(txtCedula.getText().equals("") || txtPrimerNombre.getText().equals(" ") || txtPrimerApellido.getText().equals("") || txtTelefono1.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Hay campos vacios");
        }else{
            Recepcionista miasistente = new Recepcionista();
            Cedula=txtCedula.getText();
            Nombre=txtPrimerNombre.getText();
            Segundonombre=txtSegundoNombre.getText();
            Apellido=txtPrimerApellido.getText();
            Segundoapellido=txtSegundoApellido.getText();
            Edad=spinnerEdadAsistente.getValue().toString();
            telefono1=txtTelefono1.getText();
            telefono2=txtTelefono2.getText();
            Direccion=txtDireccion.getText();
            String horario=box01.getSelectedItem().toString();
            if(generoMAsistente.isSelected()){
                genero="Hombre";
            }
            if(generoFasistente.isSelected()){
                genero="Mujer";
            }

            miasistente.setCedula(Cedula);
            miasistente.setNombre(Nombre);
            miasistente.setSegundo_nombre(Segundonombre);
            miasistente.setApellido(Apellido);
            miasistente.setSegundo_apellido(Segundoapellido);
            miasistente.setEdad(Edad);
            miasistente.setGenero(genero);
            miasistente.setTelefono(telefono1);
            miasistente.setTelefono2(telefono2);
            miasistente.setDireccion(Direccion);

            listaasistente.add(miasistente);
            Connection conn = null;
            PreparedStatement stmt = null;
            String SQL_INSERT="INSERT INTO asistentes(primernombre, segundonombre, primerapellido, segundoapellido, edad, direccion, genero, telefono, horario, cedula)VALUES ('"+Nombre+"', '"+Segundonombre+"', '"+Apellido+"', '"+Segundoapellido+"', '"+Edad+"', '"+Direccion+"', '"+genero+"', '"+telefono1+"','"+horario+"','"+Cedula+"');";
            try {
                conn = getConnection();
                stmt = conn.prepareStatement(SQL_INSERT);
                stmt.executeUpdate();
            } catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
            finally{
                try {
                    close(stmt);
                    close(conn);
                } catch (SQLException ex) {
                    ex.printStackTrace(System.out);
                }
            }

            txtDireccion.setText("");
            txtPrimerNombre.setText("");
            txtSegundoNombre.setText("");
            txtPrimerApellido.setText("");
            txtSegundoApellido.setText("");
            txtSegundoApellido.setText("");
            txtTelefono1.setText("");
            txtTelefono2.setText("");
            txtDireccion.setText("");
            new Asistentes().setVisible(true);
            this.dispose();
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoApellidoActionPerformed

    private void generoMAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoMAsistenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoMAsistenteActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void box01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box01ActionPerformed

    private void txtCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMousePressed

        txtCedula.setText("");
        txtCedula.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaMousePressed

    private void txtPrimerNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrimerNombreMousePressed
         
        txtPrimerNombre.setText("");
        txtPrimerNombre.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNombreMousePressed

    private void txtSegundoNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSegundoNombreMousePressed
     txtSegundoNombre.setText("");
        txtSegundoNombre.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoNombreMousePressed

    private void txtPrimerApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrimerApellidoMousePressed
         txtPrimerApellido.setText("");
        txtPrimerApellido.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApellidoMousePressed

    private void txtSegundoApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSegundoApellidoMousePressed
        txtSegundoApellido.setText("");
        txtSegundoApellido.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoApellidoMousePressed

    private void txtTelefono1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefono1MousePressed
    txtTelefono1.setText("");
        txtTelefono1.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefono1MousePressed

    private void txtTelefono2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefono2MousePressed
         txtTelefono2.setText("");
        txtTelefono2.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefono2MousePressed

    private void txtDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMousePressed
      txtDireccion.setText("");
        txtDireccion.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box01;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnedit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton generoFasistente;
    private javax.swing.JRadioButton generoMAsistente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spinnerEdadAsistente;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtTelefono2;
    // End of variables declaration//GEN-END:variables
}
